version : '3'

services :
  server:
    build: .
    container_name: 'calendar'
    depends_on:
     - 'database'
    ports:
     - '3002:3002'

  database:
    image: mongo:latest
    container_name: 'mongodb'
    volumes:
      - ./data:/data/db
